# Generated by Django 4.0 on 2022-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANNER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number_Of_Banner', models.IntegerField()),
                ('Size_Of_Banner', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Banner_Type', models.CharField(choices=[('Camps', 'Camps'), ('Event', 'Event')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CAMP_HELPER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('Helper', 'Helper'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=20)),
                ('Camp_Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Work', models.CharField(choices=[('Back Stage', 'Back Stage'), ('On Stage', 'On Stage'), ('Decoration', 'Decoration')], max_length=20)),
                ('Monitor_Under', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CAMPS_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('DateOfCamps', models.DateField()),
                ('Days_For_Camp', models.IntegerField()),
                ('Number_Of_Monitors', models.IntegerField()),
                ('Number_Of_Helpers', models.IntegerField()),
                ('Need_Of_Helpers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COUNCILLOR_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female')], max_length=20)),
                ('Speciality', models.CharField(choices=[('Women Violence', 'Women Violence'), ('Children Violence', 'Children Violence'), ('psychology Violence', 'psychology Violence'), ('Helth Care', 'Helth Care'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EVENT_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Date_Of_Events', models.DateField()),
                ('Number_Of_Monitors', models.IntegerField()),
                ('Number_Of_Helpers', models.IntegerField()),
                ('Need_Of_Helpers', models.IntegerField()),
                ('Event_Type', models.CharField(choices=[('Health Care', 'Health Care'), ('Women Rights', 'Women Rights'), ('Carrer Guidence', 'Carrer Guidence'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EVENT_HELPER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Helper_Type', models.CharField(choices=[('Helper', 'Helper'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=20)),
                ('Event_Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Work', models.CharField(choices=[('Back Stage', 'Back Stage'), ('On Stage', 'On Stage'), ('Decoration', 'Decoration')], max_length=20)),
                ('Monitor_Under', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FEEDBACK_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Feedback', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='HELPER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Intrested', models.CharField(choices=[('Camps', 'Camps'), ('Event', 'Event')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SPONSER_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('sponcer_type', models.CharField(choices=[('Self', 'Self'), ('Organisation', 'Organisation')], max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Sponsering_For', models.CharField(choices=[('Camps', 'Camps'), ('Event', 'Event')], max_length=20)),
                ('Amount', models.IntegerField()),
                ('Payment_Type', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UPLOAD_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About_Image', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='VICTIM_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female')], max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Victim_Type', models.CharField(choices=[('Women Violence', 'Women Violence'), ('Children Violence', 'Children Violence'), ('psychology Violence', 'psychology Violence'), ('Helth Care', 'Helth Care'), ('Other', 'Other')], max_length=20)),
                ('Cuncilor_Name', models.CharField(max_length=50)),
                ('Date_Of_Treatement', models.DateField()),
            ],
        ),
    ]
