from unicodedata import name
from django.urls import path
from.import views 

urlpatterns = [
    path('',views.home),
    path('login/',views.loginpage,name='login'),
    path('aboutpage/',views.aboutpage,name='about'),
    path('feedback/',views.feedbackPage,name='feedback'),
    path('showfeedback/',views.showfeedback,name='showfeedback'),
    path('deletefeed/<int:id>/',views.deletefeedback,name='deletefeed'),
    path('uploadpage/',views.uploadPage,name='uploadpage'),
    path('showimage/',views.showimage,name='showimage'),
    path('updateimg/<int:id>/',views.update_image,name='updateimg'),
    path('deleteimg/<int:id>/',views.delete_image,name='deleteimg'),
    path('signup/',views.SignupPage,name='signup'),
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('helperlogin/',views.helperlogin,name='helperlogin'),
    path('adminhome/',views.adminhomepage,name='adminhome'),
    path('helperhome/',views.helperhomepage,name='helperhome'),
    path('logout/',views.userlogout,name='logout'),
    path('victimpage/',views.VictimPage,name='victimpage'),
    path('VictimData/',views.ShowVictimData,name='VictimData'),
    path('victimdelete/<int:id>/',views.victim_delete_data,name='victimdelete'),
    path('victimupdate/<int:id>/',views.update_victim_data,name='victimupdate'),
    path('councilloupage/',views.CouncillorPage,name='councillorpage'),
    path('councillorData/',views.ShowCouncillorData,name='councillorData'),
    path('councillordelete/<int:id>/',views.councillor_delete_data,name='councillordelete'),
    path('councillorupdate/<int:id>/',views.update_councillor_data,name='councillorupdate'),
    path('eventpage/',views.EventPage,name='eventpage'),
    path('eventData/',views.ShowEventData,name='eventdata'),
    path('eventdelete/<int:id>/',views.event_delete_data,name='eventdelete'),
    path('eventupdate/<int:id>/',views.update_event_data,name='eventupdate'),
    path('sponsorpage/',views.SponsersPage,name='sponsorpage'),
    path('sponsorData/',views.ShowSponsorsData,name='sponsorData'),
    path('sponsorsdelete/<int:id>/',views.event_delete_data,name='sponsorsdelete'),
    path('sponsorsupdate/<int:id>/',views.update_sponsors_data,name='sponsorsupdate'),
    path('bannerpage/',views.BannerPage,name='bannerpage'),
    path('bannerData/',views.ShowBannerData,name='bannerdata'),
    path('bannerdelete/<int:id>/',views.banner_delete_data,name='bannerdelete'),
    path('bannerupdate/<int:id>/',views.update_banner_data,name='bannerupdate'),
    path('helperpage/',views.HelperPage,name='helperpage'),
    path('helperData/',views.ShowHelperData,name='helperdata'),
    path('helperdelete/<int:id>/',views.helper_delete_data,name='helperdelete'),
    path('helperupdate/<int:id>/',views.update_helper_data,name='helperupdate'),
    path('helperineventpage/',views.HelperInEventPage,name='helperineventpage'),
    path('helpereventData/',views.ShowHelperInEventData,name='helpereventdata'),
    path('helpereventdelete/<int:id>/',views.helperinevent_delete_data,name='helpereventdelete'),
    path('helpereventupdate/<int:id>/',views.update_helperevent_data,name='helpereventupdate'),
    path('helperincamppage/',views.HelperInCampPage,name='helperincamppage'),
    path('helpercampData/',views.ShowHelperInCampData,name='helpercampdata'),
    path('helpercampdelete/<int:id>/',views.helperincamp_delete_data,name='helpercampdelete'),
    path('helpercampupdate/<int:id>/',views.update_helpercamp_data,name='helpercampupdate'),

]        
